import { Voice, SliderConfig, TTSFormData } from '@/types/tts';

export const VOICE_OPTIONS: Voice[] = [
  { id: 'af-ZA-AdriNeural', name: 'Adri', language: 'Afrikaans (South Africa)', gender: 'Female' },
  { id: 'af-ZA-WillemNeural', name: 'Willem', language: 'Afrikaans (South Africa)', gender: 'Male' },
  { id: 'sq-AL-AnilaNeural', name: 'Anila', language: 'Albanian (Albania)', gender: 'Female' },
  { id: 'sq-AL-IlirNeural', name: 'Ilir', language: 'Albanian (Albania)', gender: 'Male' },
  { id: 'am-ET-AmehaNeural', name: 'Ameha', language: 'Amharic (Ethiopia)', gender: 'Male' },
  { id: 'am-ET-MekdesNeural', name: 'Mekdes', language: 'Amharic (Ethiopia)', gender: 'Female' },
  { id: 'ar-DZ-AminaNeural', name: 'Amina', language: 'Arabic (Algeria)', gender: 'Female' },
  { id: 'ar-DZ-IsmaelNeural', name: 'Ismael', language: 'Arabic (Algeria)', gender: 'Male' },
  { id: 'ar-BH-AliNeural', name: 'Ali', language: 'Arabic (Bahrain)', gender: 'Male' },
  { id: 'ar-BH-LailaNeural', name: 'Laila', language: 'Arabic (Bahrain)', gender: 'Female' },
  { id: 'ar-EG-SalmaNeural', name: 'Salma', language: 'Arabic (Egypt)', gender: 'Female' },
  { id: 'ar-EG-ShakirNeural', name: 'Shakir', language: 'Arabic (Egypt)', gender: 'Male' },
  { id: 'ar-IQ-BasselNeural', name: 'Bassel', language: 'Arabic (Iraq)', gender: 'Male' },
  { id: 'ar-IQ-RanaNeural', name: 'Rana', language: 'Arabic (Iraq)', gender: 'Female' },
  { id: 'ar-JO-SanaNeural', name: 'Sana', language: 'Arabic (Jordan)', gender: 'Female' },
  { id: 'ar-JO-TaimNeural', name: 'Taim', language: 'Arabic (Jordan)', gender: 'Male' },
  { id: 'ar-KW-FahedNeural', name: 'Fahed', language: 'Arabic (Kuwait)', gender: 'Male' },
  { id: 'ar-KW-NouraNeural', name: 'Noura', language: 'Arabic (Kuwait)', gender: 'Female' },
  { id: 'ar-LB-LaylaNeural', name: 'Layla', language: 'Arabic (Lebanon)', gender: 'Female' },
  { id: 'ar-LB-RamiNeural', name: 'Rami', language: 'Arabic (Lebanon)', gender: 'Male' },
  { id: 'ar-LY-ImanNeural', name: 'Iman', language: 'Arabic (Libya)', gender: 'Female' },
  { id: 'ar-LY-OmarNeural', name: 'Omar', language: 'Arabic (Libya)', gender: 'Male' },
  { id: 'ar-MA-JamalNeural', name: 'Jamal', language: 'Arabic (Morocco)', gender: 'Male' },
  { id: 'ar-MA-MounaNeural', name: 'Mouna', language: 'Arabic (Morocco)', gender: 'Female' },
  { id: 'ar-OM-AbdullahNeural', name: 'Abdullah', language: 'Arabic (Oman)', gender: 'Male' },
  { id: 'ar-OM-AyshaNeural', name: 'Aysha', language: 'Arabic (Oman)', gender: 'Female' },
  { id: 'ar-QA-AmalNeural', name: 'Amal', language: 'Arabic (Qatar)', gender: 'Female' },
  { id: 'ar-QA-MoazNeural', name: 'Moaz', language: 'Arabic (Qatar)', gender: 'Male' },
  { id: 'ar-SA-HamedNeural', name: 'Hamed', language: 'Arabic (Saudi Arabia)', gender: 'Male' },
  { id: 'ar-SA-ZariyahNeural', name: 'Zariyah', language: 'Arabic (Saudi Arabia)', gender: 'Female' },
  { id: 'ar-SY-AmanyNeural', name: 'Amany', language: 'Arabic (Syria)', gender: 'Female' },
  { id: 'ar-SY-LaithNeural', name: 'Laith', language: 'Arabic (Syria)', gender: 'Male' },
  { id: 'ar-TN-HediNeural', name: 'Hedi', language: 'Arabic (Tunisia)', gender: 'Male' },
  { id: 'ar-TN-ReemNeural', name: 'Reem', language: 'Arabic (Tunisia)', gender: 'Female' },
  { id: 'ar-AE-FatimaNeural', name: 'Fatima', language: 'Arabic (UAE)', gender: 'Female' },
  { id: 'ar-AE-HamdanNeural', name: 'Hamdan', language: 'Arabic (UAE)', gender: 'Male' },
  { id: 'ar-YE-MaryamNeural', name: 'Maryam', language: 'Arabic (Yemen)', gender: 'Female' },
  { id: 'ar-YE-SalehNeural', name: 'Saleh', language: 'Arabic (Yemen)', gender: 'Male' },
  { id: 'az-AZ-BabekNeural', name: 'Babek', language: 'Azerbaijani (Azerbaijan)', gender: 'Male' },
  { id: 'az-AZ-BanuNeural', name: 'Banu', language: 'Azerbaijani (Azerbaijan)', gender: 'Female' },
  { id: 'bn-BD-NabanitaNeural', name: 'Nabanita', language: 'Bengali (Bangladesh)', gender: 'Female' },
  { id: 'bn-BD-PradeepNeural', name: 'Pradeep', language: 'Bengali (Bangladesh)', gender: 'Male' },
  { id: 'bn-IN-BashkarNeural', name: 'Bashkar', language: 'Bengali (India)', gender: 'Male' },
  { id: 'bn-IN-TanishaaNeural', name: 'Tanishaa', language: 'Bengali (India)', gender: 'Female' },
  { id: 'bs-BA-GoranNeural', name: 'Goran', language: 'Bosnian (Bosnia)', gender: 'Male' },
  { id: 'bs-BA-VesnaNeural', name: 'Vesna', language: 'Bosnian (Bosnia)', gender: 'Female' },
  { id: 'bg-BG-BorislavNeural', name: 'Borislav', language: 'Bulgarian (Bulgaria)', gender: 'Male' },
  { id: 'bg-BG-KalinaNeural', name: 'Kalina', language: 'Bulgarian (Bulgaria)', gender: 'Female' },
  { id: 'my-MM-NilarNeural', name: 'Nilar', language: 'Burmese (Myanmar)', gender: 'Female' },
  { id: 'my-MM-ThihaNeural', name: 'Thiha', language: 'Burmese (Myanmar)', gender: 'Male' },
  { id: 'ca-ES-EnricNeural', name: 'Enric', language: 'Catalan (Spain)', gender: 'Male' },
  { id: 'ca-ES-JoanaNeural', name: 'Joana', language: 'Catalan (Spain)', gender: 'Female' },
  { id: 'zh-HK-HiuGaaiNeural', name: 'HiuGaai', language: 'Chinese (Hong Kong)', gender: 'Female' },
  { id: 'zh-HK-HiuMaanNeural', name: 'HiuMaan', language: 'Chinese (Hong Kong)', gender: 'Female' },
  { id: 'zh-HK-WanLungNeural', name: 'WanLung', language: 'Chinese (Hong Kong)', gender: 'Male' },
  { id: 'zh-CN-XiaoxiaoNeural', name: 'Xiaoxiao', language: 'Chinese (Mainland)', gender: 'Female' },
  { id: 'zh-CN-XiaoyiNeural', name: 'Xiaoyi', language: 'Chinese (Mainland)', gender: 'Female' },
  { id: 'zh-CN-YunjianNeural', name: 'Yunjian', language: 'Chinese (Mainland)', gender: 'Male' },
  { id: 'zh-CN-YunxiNeural', name: 'Yunxi', language: 'Chinese (Mainland)', gender: 'Male' },
  { id: 'zh-CN-YunxiaNeural', name: 'Yunxia', language: 'Chinese (Mainland)', gender: 'Male' },
  { id: 'zh-CN-YunyangNeural', name: 'Yunyang', language: 'Chinese (Mainland)', gender: 'Male' },
  { id: 'zh-CN-liaoning-XiaobeiNeural', name: 'Xiaobei', language: 'Chinese (Liaoning)', gender: 'Female' },
  { id: 'zh-TW-HsiaoChenNeural', name: 'HsiaoChen', language: 'Chinese (Taiwan)', gender: 'Female' },
  { id: 'zh-TW-YunJheNeural', name: 'YunJhe', language: 'Chinese (Taiwan)', gender: 'Male' },
  { id: 'zh-TW-HsiaoYuNeural', name: 'HsiaoYu', language: 'Chinese (Taiwan)', gender: 'Female' },
  { id: 'zh-CN-shaanxi-XiaoniNeural', name: 'Xiaoni', language: 'Chinese (Shaanxi)', gender: 'Female' },
  { id: 'hr-HR-GabrijelaNeural', name: 'Gabrijela', language: 'Croatian (Croatia)', gender: 'Female' },
  { id: 'hr-HR-SreckoNeural', name: 'Srecko', language: 'Croatian (Croatia)', gender: 'Male' },
  { id: 'cs-CZ-AntoninNeural', name: 'Antonin', language: 'Czech (Czechia)', gender: 'Male' },
  { id: 'cs-CZ-VlastaNeural', name: 'Vlasta', language: 'Czech (Czechia)', gender: 'Female' },
  { id: 'da-DK-ChristelNeural', name: 'Christel', language: 'Danish (Denmark)', gender: 'Female' },
  { id: 'da-DK-JeppeNeural', name: 'Jeppe', language: 'Danish (Denmark)', gender: 'Male' },
  { id: 'nl-BE-ArnaudNeural', name: 'Arnaud', language: 'Dutch (Belgium)', gender: 'Male' },
  { id: 'nl-BE-DenaNeural', name: 'Dena', language: 'Dutch (Belgium)', gender: 'Female' },
  { id: 'nl-NL-ColetteNeural', name: 'Colette', language: 'Dutch (Netherlands)', gender: 'Female' },
  { id: 'nl-NL-FennaNeural', name: 'Fenna', language: 'Dutch (Netherlands)', gender: 'Female' },
  { id: 'nl-NL-MaartenNeural', name: 'Maarten', language: 'Dutch (Netherlands)', gender: 'Male' },
  { id: 'en-AU-NatashaNeural', name: 'Natasha', language: 'English (Australia)', gender: 'Female' },
  { id: 'en-AU-WilliamNeural', name: 'William', language: 'English (Australia)', gender: 'Male' },
  { id: 'en-CA-ClaraNeural', name: 'Clara', language: 'English (Canada)', gender: 'Female' },
  { id: 'en-CA-LiamNeural', name: 'Liam', language: 'English (Canada)', gender: 'Male' },
  { id: 'en-HK-SamNeural', name: 'Sam', language: 'English (Hong Kong)', gender: 'Male' },
  { id: 'en-HK-YanNeural', name: 'Yan', language: 'English (Hong Kong)', gender: 'Female' },
  { id: 'en-IN-NeerjaNeural', name: 'Neerja', language: 'English (India)', gender: 'Female' },
  { id: 'en-IN-PrabhatNeural', name: 'Prabhat', language: 'English (India)', gender: 'Male' },
  { id: 'en-IE-ConnorNeural', name: 'Connor', language: 'English (Ireland)', gender: 'Male' },
  { id: 'en-IE-EmilyNeural', name: 'Emily', language: 'English (Ireland)', gender: 'Female' },
  { id: 'en-KE-AsiliaNeural', name: 'Asilia', language: 'English (Kenya)', gender: 'Female' },
  { id: 'en-KE-ChilembaNeural', name: 'Chilemba', language: 'English (Kenya)', gender: 'Male' },
  { id: 'en-NZ-MitchellNeural', name: 'Mitchell', language: 'English (New Zealand)', gender: 'Male' },
  { id: 'en-NZ-MollyNeural', name: 'Molly', language: 'English (New Zealand)', gender: 'Female' },
  { id: 'en-NG-AbeoNeural', name: 'Abeo', language: 'English (Nigeria)', gender: 'Male' },
  { id: 'en-NG-EzinneNeural', name: 'Ezinne', language: 'English (Nigeria)', gender: 'Female' },
  { id: 'en-PH-JamesNeural', name: 'James', language: 'English (Philippines)', gender: 'Male' },
  { id: 'en-PH-RosaNeural', name: 'Rosa', language: 'English (Philippines)', gender: 'Female' },
  { id: 'en-SG-LunaNeural', name: 'Luna', language: 'English (Singapore)', gender: 'Female' },
  { id: 'en-SG-WayneNeural', name: 'Wayne', language: 'English (Singapore)', gender: 'Male' },
  { id: 'en-ZA-LeahNeural', name: 'Leah', language: 'English (South Africa)', gender: 'Female' },
  { id: 'en-ZA-LukeNeural', name: 'Luke', language: 'English (South Africa)', gender: 'Male' },
  { id: 'en-TZ-ElimuNeural', name: 'Elimu', language: 'English (Tanzania)', gender: 'Male' },
  { id: 'en-TZ-ImaniNeural', name: 'Imani', language: 'English (Tanzania)', gender: 'Female' },
  { id: 'en-GB-LibbyNeural', name: 'Libby', language: 'English (UK)', gender: 'Female' },
  { id: 'en-GB-MaisieNeural', name: 'Maisie', language: 'English (UK)', gender: 'Female' },
  { id: 'en-GB-RyanNeural', name: 'Ryan', language: 'English (UK)', gender: 'Male' },
  { id: 'en-GB-SoniaNeural', name: 'Sonia', language: 'English (UK)', gender: 'Female' },
  { id: 'en-GB-ThomasNeural', name: 'Thomas', language: 'English (UK)', gender: 'Male' },
  { id: 'en-US-AriaNeural', name: 'Aria', language: 'English (US)', gender: 'Female' },
  { id: 'en-US-AnaNeural', name: 'Ana', language: 'English (US)', gender: 'Female' },
  { id: 'en-US-ChristopherNeural', name: 'Christopher', language: 'English (US)', gender: 'Male' },
  { id: 'en-US-EricNeural', name: 'Eric', language: 'English (US)', gender: 'Male' },
  { id: 'en-US-GuyNeural', name: 'Guy', language: 'English (US)', gender: 'Male' },
  { id: 'en-US-JennyNeural', name: 'Jenny', language: 'English (US)', gender: 'Female' },
  { id: 'en-US-MichelleNeural', name: 'Michelle', language: 'English (US)', gender: 'Female' },
  { id: 'en-US-RogerNeural', name: 'Roger', language: 'English (US)', gender: 'Male' },
  { id: 'en-US-SteffanNeural', name: 'Steffan', language: 'English (US)', gender: 'Male' },
  { id: 'et-EE-AnuNeural', name: 'Anu', language: 'Estonian (Estonia)', gender: 'Female' },
  { id: 'et-EE-KertNeural', name: 'Kert', language: 'Estonian (Estonia)', gender: 'Male' },
  { id: 'fil-PH-AngeloNeural', name: 'Angelo', language: 'Filipino (Philippines)', gender: 'Male' },
  { id: 'fil-PH-BlessicaNeural', name: 'Blessica', language: 'Filipino (Philippines)', gender: 'Female' },
  { id: 'fi-FI-HarriNeural', name: 'Harri', language: 'Finnish (Finland)', gender: 'Male' },
  { id: 'fi-FI-NooraNeural', name: 'Noora', language: 'Finnish (Finland)', gender: 'Female' },
  { id: 'fr-BE-CharlineNeural', name: 'Charline', language: 'French (Belgium)', gender: 'Female' },
  { id: 'fr-BE-GerardNeural', name: 'Gerard', language: 'French (Belgium)', gender: 'Male' },
  { id: 'fr-CA-AntoineNeural', name: 'Antoine', language: 'French (Canada)', gender: 'Male' },
  { id: 'fr-CA-JeanNeural', name: 'Jean', language: 'French (Canada)', gender: 'Male' },
  { id: 'fr-CA-SylvieNeural', name: 'Sylvie', language: 'French (Canada)', gender: 'Female' },
  { id: 'fr-FR-DeniseNeural', name: 'Denise', language: 'French (France)', gender: 'Female' },
  { id: 'fr-FR-EloiseNeural', name: 'Eloise', language: 'French (France)', gender: 'Female' },
  { id: 'fr-FR-HenriNeural', name: 'Henri', language: 'French (France)', gender: 'Male' },
  { id: 'fr-CH-ArianeNeural', name: 'Ariane', language: 'French (Switzerland)', gender: 'Female' },
  { id: 'fr-CH-FabriceNeural', name: 'Fabrice', language: 'French (Switzerland)', gender: 'Male' },
  { id: 'gl-ES-RoiNeural', name: 'Roi', language: 'Galician (Spain)', gender: 'Male' },
  { id: 'gl-ES-SabelaNeural', name: 'Sabela', language: 'Galician (Spain)', gender: 'Female' },
  { id: 'ka-GE-EkaNeural', name: 'Eka', language: 'Georgian (Georgia)', gender: 'Female' },
  { id: 'ka-GE-GiorgiNeural', name: 'Giorgi', language: 'Georgian (Georgia)', gender: 'Male' },
  { id: 'de-AT-IngridNeural', name: 'Ingrid', language: 'German (Austria)', gender: 'Female' },
  { id: 'de-AT-JonasNeural', name: 'Jonas', language: 'German (Austria)', gender: 'Male' },
  { id: 'de-DE-AmalaNeural', name: 'Amala', language: 'German (Germany)', gender: 'Female' },
  { id: 'de-DE-ConradNeural', name: 'Conrad', language: 'German (Germany)', gender: 'Male' },
  { id: 'de-DE-KatjaNeural', name: 'Katja', language: 'German (Germany)', gender: 'Female' },
  { id: 'de-DE-KillianNeural', name: 'Killian', language: 'German (Germany)', gender: 'Male' },
  { id: 'de-CH-JanNeural', name: 'Jan', language: 'German (Switzerland)', gender: 'Male' },
  { id: 'de-CH-LeniNeural', name: 'Leni', language: 'German (Switzerland)', gender: 'Female' },
  { id: 'el-GR-AthinaNeural', name: 'Athina', language: 'Greek (Greece)', gender: 'Female' },
  { id: 'el-GR-NestorasNeural', name: 'Nestoras', language: 'Greek (Greece)', gender: 'Male' },
  { id: 'gu-IN-DhwaniNeural', name: 'Dhwani', language: 'Gujarati (India)', gender: 'Female' },
  { id: 'gu-IN-NiranjanNeural', name: 'Niranjan', language: 'Gujarati (India)', gender: 'Male' },
  { id: 'he-IL-AvriNeural', name: 'Avri', language: 'Hebrew (Israel)', gender: 'Male' },
  { id: 'he-IL-HilaNeural', name: 'Hila', language: 'Hebrew (Israel)', gender: 'Female' },
  { id: 'hi-IN-MadhurNeural', name: 'Madhur', language: 'Hindi (India)', gender: 'Male' },
  { id: 'hi-IN-SwaraNeural', name: 'Swara', language: 'Hindi (India)', gender: 'Female' },
  { id: 'hu-HU-NoemiNeural', name: 'Noemi', language: 'Hungarian (Hungary)', gender: 'Female' },
  { id: 'hu-HU-TamasNeural', name: 'Tamas', language: 'Hungarian (Hungary)', gender: 'Male' },
  { id: 'is-IS-GudrunNeural', name: 'Gudrun', language: 'Icelandic (Iceland)', gender: 'Female' },
  { id: 'is-IS-GunnarNeural', name: 'Gunnar', language: 'Icelandic (Iceland)', gender: 'Male' },
  { id: 'id-ID-ArdiNeural', name: 'Ardi', language: 'Indonesian (Indonesia)', gender: 'Male' },
  { id: 'id-ID-GadisNeural', name: 'Gadis', language: 'Indonesian (Indonesia)', gender: 'Female' },
  { id: 'ga-IE-ColmNeural', name: 'Colm', language: 'Irish (Ireland)', gender: 'Male' },
  { id: 'ga-IE-OrlaNeural', name: 'Orla', language: 'Irish (Ireland)', gender: 'Female' },
  { id: 'it-IT-DiegoNeural', name: 'Diego', language: 'Italian (Italy)', gender: 'Male' },
  { id: 'it-IT-ElsaNeural', name: 'Elsa', language: 'Italian (Italy)', gender: 'Female' },
  { id: 'it-IT-IsabellaNeural', name: 'Isabella', language: 'Italian (Italy)', gender: 'Female' },
  { id: 'ja-JP-KeitaNeural', name: 'Keita', language: 'Japanese (Japan)', gender: 'Male' },
  { id: 'ja-JP-NanamiNeural', name: 'Nanami', language: 'Japanese (Japan)', gender: 'Female' },
  { id: 'jv-ID-DimasNeural', name: 'Dimas', language: 'Javanese (Indonesia)', gender: 'Male' },
  { id: 'jv-ID-SitiNeural', name: 'Siti', language: 'Javanese (Indonesia)', gender: 'Female' },
  { id: 'kn-IN-GaganNeural', name: 'Gagan', language: 'Kannada (India)', gender: 'Male' },
  { id: 'kn-IN-SapnaNeural', name: 'Sapna', language: 'Kannada (India)', gender: 'Female' },
  { id: 'kk-KZ-AigulNeural', name: 'Aigul', language: 'Kazakh (Kazakhstan)', gender: 'Female' },
  { id: 'kk-KZ-DauletNeural', name: 'Daulet', language: 'Kazakh (Kazakhstan)', gender: 'Male' },
  { id: 'km-KH-PisethNeural', name: 'Piseth', language: 'Khmer (Cambodia)', gender: 'Male' },
  { id: 'km-KH-SreymomNeural', name: 'Sreymom', language: 'Khmer (Cambodia)', gender: 'Female' },
  { id: 'ko-KR-InJoonNeural', name: 'InJoon', language: 'Korean (Korea)', gender: 'Male' },
  { id: 'ko-KR-SunHiNeural', name: 'SunHi', language: 'Korean (Korea)', gender: 'Female' },
  { id: 'lo-LA-ChanthavongNeural', name: 'Chanthavong', language: 'Lao (Laos)', gender: 'Male' },
  { id: 'lo-LA-KeomanyNeural', name: 'Keomany', language: 'Lao (Laos)', gender: 'Female' },
  { id: 'lv-LV-EveritaNeural', name: 'Everita', language: 'Latvian (Latvia)', gender: 'Female' },
  { id: 'lv-LV-NilsNeural', name: 'Nils', language: 'Latvian (Latvia)', gender: 'Male' },
  { id: 'lt-LT-LeonasNeural', name: 'Leonas', language: 'Lithuanian (Lithuania)', gender: 'Male' },
  { id: 'lt-LT-OnaNeural', name: 'Ona', language: 'Lithuanian (Lithuania)', gender: 'Female' },
  { id: 'mk-MK-AleksandarNeural', name: 'Aleksandar', language: 'Macedonian (Macedonia)', gender: 'Male' },
  { id: 'mk-MK-MarijaNeural', name: 'Marija', language: 'Macedonian (Macedonia)', gender: 'Female' },
  { id: 'ms-MY-OsmanNeural', name: 'Osman', language: 'Malay (Malaysia)', gender: 'Male' },
  { id: 'ms-MY-YasminNeural', name: 'Yasmin', language: 'Malay (Malaysia)', gender: 'Female' },
  { id: 'ml-IN-MidhunNeural', name: 'Midhun', language: 'Malayalam (India)', gender: 'Male' },
  { id: 'ml-IN-SobhanaNeural', name: 'Sobhana', language: 'Malayalam (India)', gender: 'Female' },
  { id: 'mt-MT-GraceNeural', name: 'Grace', language: 'Maltese (Malta)', gender: 'Female' },
  { id: 'mt-MT-JosephNeural', name: 'Joseph', language: 'Maltese (Malta)', gender: 'Male' },
  { id: 'mr-IN-AarohiNeural', name: 'Aarohi', language: 'Marathi (India)', gender: 'Female' },
  { id: 'mr-IN-ManoharNeural', name: 'Manohar', language: 'Marathi (India)', gender: 'Male' },
  { id: 'mn-MN-BataaNeural', name: 'Bataa', language: 'Mongolian (Mongolia)', gender: 'Male' },
  { id: 'mn-MN-YesuiNeural', name: 'Yesui', language: 'Mongolian (Mongolia)', gender: 'Female' },
  { id: 'ne-NP-HemkalaNeural', name: 'Hemkala', language: 'Nepali (Nepal)', gender: 'Female' },
  { id: 'ne-NP-SagarNeural', name: 'Sagar', language: 'Nepali (Nepal)', gender: 'Male' },
  { id: 'nb-NO-FinnNeural', name: 'Finn', language: 'Norwegian (Norway)', gender: 'Male' },
  { id: 'nb-NO-PernilleNeural', name: 'Pernille', language: 'Norwegian (Norway)', gender: 'Female' },
  { id: 'ps-AF-GulNawazNeural', name: 'GulNawaz', language: 'Pashto (Afghanistan)', gender: 'Male' },
  { id: 'ps-AF-LatifaNeural', name: 'Latifa', language: 'Pashto (Afghanistan)', gender: 'Female' },
  { id: 'fa-IR-DilaraNeural', name: 'Dilara', language: 'Persian (Iran)', gender: 'Female' },
  { id: 'fa-IR-FaridNeural', name: 'Farid', language: 'Persian (Iran)', gender: 'Male' },
  { id: 'pl-PL-MarekNeural', name: 'Marek', language: 'Polish (Poland)', gender: 'Male' },
  { id: 'pl-PL-ZofiaNeural', name: 'Zofia', language: 'Polish (Poland)', gender: 'Female' },
  { id: 'pt-BR-AntonioNeural', name: 'Antonio', language: 'Portuguese (Brazil)', gender: 'Male' },
  { id: 'pt-BR-FranciscaNeural', name: 'Francisca', language: 'Portuguese (Brazil)', gender: 'Female' },
  { id: 'pt-PT-DuarteNeural', name: 'Duarte', language: 'Portuguese (Portugal)', gender: 'Male' },
  { id: 'pt-PT-RaquelNeural', name: 'Raquel', language: 'Portuguese (Portugal)', gender: 'Female' },
  { id: 'ro-RO-AlinaNeural', name: 'Alina', language: 'Romanian (Romania)', gender: 'Female' },
  { id: 'ro-RO-EmilNeural', name: 'Emil', language: 'Romanian (Romania)', gender: 'Male' },
  { id: 'ru-RU-DmitryNeural', name: 'Dmitry', language: 'Russian (Russia)', gender: 'Male' },
  { id: 'ru-RU-SvetlanaNeural', name: 'Svetlana', language: 'Russian (Russia)', gender: 'Female' },
  { id: 'sr-RS-NicholasNeural', name: 'Nicholas', language: 'Serbian (Serbia)', gender: 'Male' },
  { id: 'sr-RS-SophieNeural', name: 'Sophie', language: 'Serbian (Serbia)', gender: 'Female' },
  { id: 'si-LK-SameeraNeural', name: 'Sameera', language: 'Sinhala (Sri Lanka)', gender: 'Male' },
  { id: 'si-LK-ThiliniNeural', name: 'Thilini', language: 'Sinhala (Sri Lanka)', gender: 'Female' },
  { id: 'sk-SK-LukasNeural', name: 'Lukas', language: 'Slovak (Slovakia)', gender: 'Male' },
  { id: 'sk-SK-ViktoriaNeural', name: 'Viktoria', language: 'Slovak (Slovakia)', gender: 'Female' },
  { id: 'sl-SI-PetraNeural', name: 'Petra', language: 'Slovenian (Slovenia)', gender: 'Female' },
  { id: 'sl-SI-RokNeural', name: 'Rok', language: 'Slovenian (Slovenia)', gender: 'Male' },
  { id: 'so-SO-MuuseNeural', name: 'Muuse', language: 'Somali (Somalia)', gender: 'Male' },
  { id: 'so-SO-UbaxNeural', name: 'Ubax', language: 'Somali (Somalia)', gender: 'Female' },
  { id: 'es-AR-ElenaNeural', name: 'Elena', language: 'Spanish (Argentina)', gender: 'Female' },
  { id: 'es-AR-TomasNeural', name: 'Tomas', language: 'Spanish (Argentina)', gender: 'Male' },
  { id: 'es-BO-MarceloNeural', name: 'Marcelo', language: 'Spanish (Bolivia)', gender: 'Male' },
  { id: 'es-BO-SofiaNeural', name: 'Sofia', language: 'Spanish (Bolivia)', gender: 'Female' },
  { id: 'es-CL-CatalinaNeural', name: 'Catalina', language: 'Spanish (Chile)', gender: 'Female' },
  { id: 'es-CL-LorenzoNeural', name: 'Lorenzo', language: 'Spanish (Chile)', gender: 'Male' },
  { id: 'es-CO-GonzaloNeural', name: 'Gonzalo', language: 'Spanish (Colombia)', gender: 'Male' },
  { id: 'es-CO-SalomeNeural', name: 'Salome', language: 'Spanish (Colombia)', gender: 'Female' },
  { id: 'es-CR-JuanNeural', name: 'Juan', language: 'Spanish (Costa Rica)', gender: 'Male' },
  { id: 'es-CR-MariaNeural', name: 'Maria', language: 'Spanish (Costa Rica)', gender: 'Female' },
  { id: 'es-CU-BelkysNeural', name: 'Belkys', language: 'Spanish (Cuba)', gender: 'Female' },
  { id: 'es-CU-ManuelNeural', name: 'Manuel', language: 'Spanish (Cuba)', gender: 'Male' },
  { id: 'es-DO-EmilioNeural', name: 'Emilio', language: 'Spanish (Dominican Republic)', gender: 'Male' },
  { id: 'es-DO-RamonaNeural', name: 'Ramona', language: 'Spanish (Dominican Republic)', gender: 'Female' },
  { id: 'es-EC-AndreaNeural', name: 'Andrea', language: 'Spanish (Ecuador)', gender: 'Female' },
  { id: 'es-EC-LuisNeural', name: 'Luis', language: 'Spanish (Ecuador)', gender: 'Male' },
  { id: 'es-SV-LorenaNeural', name: 'Lorena', language: 'Spanish (El Salvador)', gender: 'Female' },
  { id: 'es-SV-RodrigoNeural', name: 'Rodrigo', language: 'Spanish (El Salvador)', gender: 'Male' },
  { id: 'es-GQ-JavierNeural', name: 'Javier', language: 'Spanish (Equatorial Guinea)', gender: 'Male' },
  { id: 'es-GQ-TeresaNeural', name: 'Teresa', language: 'Spanish (Equatorial Guinea)', gender: 'Female' },
  { id: 'es-GT-AndresNeural', name: 'Andres', language: 'Spanish (Guatemala)', gender: 'Male' },
  { id: 'es-GT-MartaNeural', name: 'Marta', language: 'Spanish (Guatemala)', gender: 'Female' },
  { id: 'es-HN-CarlosNeural', name: 'Carlos', language: 'Spanish (Honduras)', gender: 'Male' },
  { id: 'es-HN-KarlaNeural', name: 'Karla', language: 'Spanish (Honduras)', gender: 'Female' },
  { id: 'es-MX-DaliaNeural', name: 'Dalia', language: 'Spanish (Mexico)', gender: 'Female' },
  { id: 'es-MX-JorgeNeural', name: 'Jorge', language: 'Spanish (Mexico)', gender: 'Male' },
  { id: 'es-NI-FedericoNeural', name: 'Federico', language: 'Spanish (Nicaragua)', gender: 'Male' },
  { id: 'es-NI-YolandaNeural', name: 'Yolanda', language: 'Spanish (Nicaragua)', gender: 'Female' },
  { id: 'es-PA-MargaritaNeural', name: 'Margarita', language: 'Spanish (Panama)', gender: 'Female' },
  { id: 'es-PA-RobertoNeural', name: 'Roberto', language: 'Spanish (Panama)', gender: 'Male' },
  { id: 'es-PY-MarioNeural', name: 'Mario', language: 'Spanish (Paraguay)', gender: 'Male' },
  { id: 'es-PY-TaniaNeural', name: 'Tania', language: 'Spanish (Paraguay)', gender: 'Female' },
  { id: 'es-PE-AlexNeural', name: 'Alex', language: 'Spanish (Peru)', gender: 'Male' },
  { id: 'es-PE-CamilaNeural', name: 'Camila', language: 'Spanish (Peru)', gender: 'Female' },
  { id: 'es-PR-KarinaNeural', name: 'Karina', language: 'Spanish (Puerto Rico)', gender: 'Female' },
  { id: 'es-PR-VictorNeural', name: 'Victor', language: 'Spanish (Puerto Rico)', gender: 'Male' },
  { id: 'es-ES-AlvaroNeural', name: 'Alvaro', language: 'Spanish (Spain)', gender: 'Male' },
  { id: 'es-ES-ElviraNeural', name: 'Elvira', language: 'Spanish (Spain)', gender: 'Female' },
  { id: 'es-US-AlonsoNeural', name: 'Alonso', language: 'Spanish (US)', gender: 'Male' },
  { id: 'es-US-PalomaNeural', name: 'Paloma', language: 'Spanish (US)', gender: 'Female' },
  { id: 'es-UY-MateoNeural', name: 'Mateo', language: 'Spanish (Uruguay)', gender: 'Male' },
  { id: 'es-UY-ValentinaNeural', name: 'Valentina', language: 'Spanish (Uruguay)', gender: 'Female' },
  { id: 'es-VE-PaolaNeural', name: 'Paola', language: 'Spanish (Venezuela)', gender: 'Female' },
  { id: 'es-VE-SebastianNeural', name: 'Sebastian', language: 'Spanish (Venezuela)', gender: 'Male' },
  { id: 'su-ID-JajangNeural', name: 'Jajang', language: 'Sundanese (Indonesia)', gender: 'Male' },
  { id: 'su-ID-TutiNeural', name: 'Tuti', language: 'Sundanese (Indonesia)', gender: 'Female' },
  { id: 'sw-KE-RafikiNeural', name: 'Rafiki', language: 'Swahili (Kenya)', gender: 'Male' },
  { id: 'sw-KE-ZuriNeural', name: 'Zuri', language: 'Swahili (Kenya)', gender: 'Female' },
  { id: 'sw-TZ-DaudiNeural', name: 'Daudi', language: 'Swahili (Tanzania)', gender: 'Male' },
  { id: 'sw-TZ-RehemaNeural', name: 'Rehema', language: 'Swahili (Tanzania)', gender: 'Female' },
  { id: 'sv-SE-MattiasNeural', name: 'Mattias', language: 'Swedish (Sweden)', gender: 'Male' },
  { id: 'sv-SE-SofieNeural', name: 'Sofie', language: 'Swedish (Sweden)', gender: 'Female' },
  { id: 'ta-IN-PallaviNeural', name: 'Pallavi', language: 'Tamil (India)', gender: 'Female' },
  { id: 'ta-IN-ValluvarNeural', name: 'Valluvar', language: 'Tamil (India)', gender: 'Male' },
  { id: 'ta-MY-KaniNeural', name: 'Kani', language: 'Tamil (Malaysia)', gender: 'Female' },
  { id: 'ta-MY-SuryaNeural', name: 'Surya', language: 'Tamil (Malaysia)', gender: 'Male' },
  { id: 'ta-SG-AnbuNeural', name: 'Anbu', language: 'Tamil (Singapore)', gender: 'Male' },
  { id: 'ta-SG-VenbaNeural', name: 'Venba', language: 'Tamil (Singapore)', gender: 'Female' },
  { id: 'ta-LK-KumarNeural', name: 'Kumar', language: 'Tamil (Sri Lanka)', gender: 'Male' },
  { id: 'ta-LK-SaranyaNeural', name: 'Saranya', language: 'Tamil (Sri Lanka)', gender: 'Female' },
  { id: 'te-IN-MohanNeural', name: 'Mohan', language: 'Telugu (India)', gender: 'Male' },
  { id: 'te-IN-ShrutiNeural', name: 'Shruti', language: 'Telugu (India)', gender: 'Female' },
  { id: 'th-TH-NiwatNeural', name: 'Niwat', language: 'Thai (Thailand)', gender: 'Male' },
  { id: 'th-TH-PremwadeeNeural', name: 'Premwadee', language: 'Thai (Thailand)', gender: 'Female' },
  { id: 'tr-TR-AhmetNeural', name: 'Ahmet', language: 'Turkish (Turkey)', gender: 'Male' },
  { id: 'tr-TR-EmelNeural', name: 'Emel', language: 'Turkish (Turkey)', gender: 'Female' },
  { id: 'uk-UA-OstapNeural', name: 'Ostap', language: 'Ukrainian (Ukraine)', gender: 'Male' },
  { id: 'uk-UA-PolinaNeural', name: 'Polina', language: 'Ukrainian (Ukraine)', gender: 'Female' },
  { id: 'ur-IN-GulNeural', name: 'Gul', language: 'Urdu (India)', gender: 'Female' },
  { id: 'ur-IN-SalmanNeural', name: 'Salman', language: 'Urdu (India)', gender: 'Male' },
  { id: 'ur-PK-AsadNeural', name: 'Asad', language: 'Urdu (Pakistan)', gender: 'Male' },
  { id: 'ur-PK-UzmaNeural', name: 'Uzma', language: 'Urdu (Pakistan)', gender: 'Female' },
  { id: 'uz-UZ-MadinaNeural', name: 'Madina', language: 'Uzbek (Uzbekistan)', gender: 'Female' },
  { id: 'uz-UZ-SardorNeural', name: 'Sardor', language: 'Uzbek (Uzbekistan)', gender: 'Male' },
  { id: 'vi-VN-HoaiMyNeural', name: 'HoaiMy', language: 'Vietnamese (Vietnam)', gender: 'Female' },
  { id: 'vi-VN-NamMinhNeural', name: 'NamMinh', language: 'Vietnamese (Vietnam)', gender: 'Male' },
  { id: 'cy-GB-AledNeural', name: 'Aled', language: 'Welsh (UK)', gender: 'Male' },
  { id: 'cy-GB-NiaNeural', name: 'Nia', language: 'Welsh (UK)', gender: 'Female' },
  { id: 'zu-ZA-ThandoNeural', name: 'Thando', language: 'Zulu (South Africa)', gender: 'Male' },
  { id: 'zu-ZA-ThembaNeural', name: 'Themba', language: 'Zulu (South Africa)', gender: 'Male' },
];

export const LANGUAGE_OPTIONS = Array.from(
  new Set(VOICE_OPTIONS.map(v => v.language))
).map(lang => ({
  id: lang,
  name: lang,
})).sort((a, b) => a.name.localeCompare(b.name));

export const SLIDER_CONFIGS: SliderConfig[] = [
  { label: 'Rate', name: 'rate', min: -50, max: 50, step: 1, unit: '%' },
  { label: 'Volume', name: 'volume', min: -50, max: 50, step: 1, unit: '%' },
  { label: 'Pitch', name: 'pitch', min: -50, max: 50, step: 1, unit: 'Hz' },
];

export const INITIAL_FORM_DATA: TTSFormData = {
  title: 'My First TTS Project',
  input_text: '',
  voice_name: 'en-US-AriaNeural',
  language: 'English (US)',
  rate: 0,
  volume: 0,
  pitch: 0,
};